"""Added account table

Revision ID: 052718bb529e
Revises: 8e489cbb35a0
Create Date: 2022-04-26 09:53:06.166357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052718bb529e'
down_revision = '8e489cbb35a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
