"""Added account table

Revision ID: 8e489cbb35a0
Revises: 8e5232e7ae97
Create Date: 2022-04-26 09:47:53.787916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e489cbb35a0'
down_revision = '8e5232e7ae97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
