"""Added account table

Revision ID: 8e5232e7ae97
Revises: 6859d75d06fa
Create Date: 2022-04-26 09:28:07.865541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5232e7ae97'
down_revision = '6859d75d06fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_name', sa.String(), nullable=True))
    op.add_column('students', sa.Column('student_age', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('classroom_id', sa.Integer(), nullable=True))
    op.drop_constraint('students_class_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'classrooms', ['classroom_id'], ['classroom_id'])
    op.drop_column('students', 'class_id')
    op.drop_column('students', 'name_st')
    op.drop_column('students', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('name_st', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_class_id_fkey', 'students', 'classrooms', ['class_id'], ['classroom_id'])
    op.drop_column('students', 'classroom_id')
    op.drop_column('students', 'student_age')
    op.drop_column('students', 'student_name')
    # ### end Alembic commands ###
